version: "3.7"
services:
    db:
        restart: always
        build:
            context: .
            dockerfile: dockers/db/Dockerfile
        hostname: db
        environment:
            - POSTGRES_PASSWORD=scraper_123
            - POSTGRES_USER=scraper
            - POSTGRES_DB=scraper
        healthcheck:
            test: ["CMD", "psql", "scraper", "-U", "scraper", "-c", "SELECT 1"]
            interval: 3s
            timeout: 3s
            start_period: 3s
            retries: 20
    app:
        depends_on:
            db:
                condition: service_healthy
        restart: always
        build:
            context: .
            dockerfile: dockers/app/Dockerfile
        volumes:
            - files:/app/orders
        environment:
            - CONNSTR=dbname=scraper user=scraper password=scraper_123 host=db
        command: ["waitress-serve", "--port", "3021", "--host", "0.0.0.0", "app:app"]
        ports:
            - "3021:3021"
    maker:
        depends_on:
            db:
                condition: service_healthy
        restart: always
        build:
            context: .
            dockerfile: dockers/maker/Dockerfile
        volumes:
            - files:/maker/orders
        environment:
            - CONNSTR=dbname=scraper user=scraper password=scraper_123 host=db
        command: ["./maker.py"]
volumes:
    files:
